
package:
  name: osmctools
  version: "0.2.1"

source:
  fn: osmctools-0.9.tar.gz
  url: https://gitlab.com/osm-c-tools/osmctools/-/archive/0.9/osmctools-0.9.tar.gz

channels:
  - conda-forge

requirements:
  build:
    - autoconf  [not win]
    - automake  [not win]

about:
  home: https://github.com/davidcaron/osmctools
  summary: Unofficial osmctools binaries
  license: MIT